/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: o processo está de pé. Não toca no banco.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: o banco responde.
         */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Related Products
         * @description Sugestões para quem está vendo este produto.
         *
         *     O filtro `Product.id != product_id` é o ponto: sem ele, o primeiro
         *     "relacionado" é o próprio produto que o cliente já está olhando.
         */
        get: operations["related_products_api_products__product_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cart
         * @description Carrinho do visitante.
         *
         *     Sem header, ou com um id desconhecido, devolve carrinho vazio com
         *     `id: null` — nunca 404, e **sem criar registro**. Assim um cliente mal
         *     configurado gera "carrinho sempre vazio", que é diagnosticável, em vez de
         *     uma enxurrada de pedidos órfãos no banco.
         */
        get: operations["get_cart_api_cart_get"];
        put?: never;
        post?: never;
        /** Clear Cart */
        delete: operations["clear_cart_api_cart_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Item
         * @description Adiciona um produto. Cria o carrinho se o visitante ainda não tem um.
         */
        post: operations["add_item_api_cart_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_cart_items__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Item
         * @description Altera a quantidade. Zero remove o item.
         *
         *     Só alcança item do próprio carrinho — item de outro visitante devolve 404.
         */
        patch: operations["update_item_api_cart_items__item_id__patch"];
        trace?: never;
    };
    "/api/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout
         * @description Fecha o carrinho do visitante identificado pelo header `X-Cart-Id`.
         *
         *     Os dados de cartão chegam aqui, são validados, autorizam o pagamento e são
         *     descartados: só bandeira e últimos quatro dígitos ficam no pedido.
         */
        post: operations["checkout_api_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Order
         * @description Consulta um pedido fechado pelo seu UUID.
         *
         *     A consulta é por `uuid`, não pelo `order_number` de 6 dígitos: 900 mil
         *     valores são varríveis em minutos, e a resposta traz nome, e-mail e
         *     endereço do comprador.
         */
        get: operations["get_order_api_orders__order_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCartItemIn */
        AddCartItemIn: {
            /** Product Id */
            product_id: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** CartItemOut */
        CartItemOut: {
            /** Id */
            id: number;
            product: components["schemas"]["ProductSummary"];
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Line Total */
            line_total: string;
        };
        /**
         * CartOut
         * @description O carrinho inteiro.
         *
         *     Toda mutação devolve este objeto completo — o cliente nunca precisa
         *     refazer um GET depois de adicionar, alterar ou remover item, e os totais
         *     não têm como divergir dos itens.
         */
        CartOut: {
            /**
             * Id
             * @description UUID do carrinho (header X-Cart-Id)
             */
            id?: string | null;
            /** Items */
            items?: components["schemas"]["CartItemOut"][];
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /**
             * Subtotal
             * @default 0.00
             */
            subtotal: string;
            /**
             * Shipping
             * @default 0.00
             */
            shipping: string;
            /**
             * Total
             * @default 0.00
             */
            total: string;
        };
        /** CheckoutIn */
        CheckoutIn: {
            customer: components["schemas"]["CustomerIn"];
            shipping_address: components["schemas"]["ShippingAddressIn"];
            payment: components["schemas"]["PaymentIn"];
        };
        /** CustomerIn */
        CustomerIn: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Mobile */
            mobile: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** OrderItemOut */
        OrderItemOut: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /** Line Total */
            line_total: string;
        };
        /** OrderOut */
        OrderOut: {
            /** Order Uuid */
            order_uuid: string;
            /** Order Number */
            order_number?: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Paid At */
            paid_at?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Email */
            customer_email?: string | null;
            /** Address1 */
            address1?: string | null;
            /** Address2 */
            address2?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Country */
            country?: string | null;
            /** Zip Code */
            zip_code?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Items */
            items: components["schemas"]["OrderItemOut"][];
            /** Subtotal */
            subtotal: string;
            /** Shipping */
            shipping: string;
            /** Total */
            total: string;
            payment: components["schemas"]["PaymentOut"];
        };
        /**
         * PaymentIn
         * @description Dados do cartão.
         *
         *     Write-only: entram, são validados, autorizam o pagamento e são
         *     descartados. Nada aqui chega ao banco — ver ADR 0004.
         *
         *     `card_number` e `cvv` são `SecretStr` para não aparecerem em log, `repr`
         *     ou traceback. A sanitização da resposta 422 (que por padrão ecoa o valor
         *     rejeitado) está em `app/errors.py`.
         */
        PaymentIn: {
            /** Card Name */
            card_name: string;
            /**
             * Card Number
             * Format: password
             */
            card_number: string;
            /**
             * Expiry Date
             * @description MM/YY
             */
            expiry_date: string;
            /**
             * Cvv
             * Format: password
             */
            cvv: string;
        };
        /**
         * PaymentOut
         * @description O que é seguro contar sobre o pagamento.
         *
         *     Bandeira e últimos quatro dígitos bastam para o cliente reconhecer o
         *     cartão e para o suporte identificar a transação. Nada além disso existe
         *     no banco.
         */
        PaymentOut: {
            /** Brand */
            brand?: string | null;
            /** Last4 */
            last4?: string | null;
        };
        /** ProductListOut */
        ProductListOut: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
        };
        /**
         * ProductOut
         * @description Produto no catálogo e no detalhe.
         */
        ProductOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Image */
            image?: string | null;
            /** Price */
            price: string;
            /** Short Description */
            short_description?: string | null;
            /** Description */
            description?: string | null;
            /** Image Url */
            readonly image_url: string | null;
        };
        /**
         * ProductSummary
         * @description Produto como aparece dentro de um item de carrinho.
         */
        ProductSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Image */
            image?: string | null;
            /** Image Url */
            readonly image_url: string | null;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** ShippingAddressIn */
        ShippingAddressIn: {
            /** Address1 */
            address1: string;
            /** Address2 */
            address2?: string | null;
            /** City */
            city: string;
            /** State */
            state: string;
            /**
             * Country
             * @default Brasil
             */
            country: string;
            /** Zip Code */
            zip_code: string;
        };
        /** UpdateCartItemIn */
        UpdateCartItemIn: {
            /** Quantity */
            quantity: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_products_api_products__product_id__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_api_cart_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID do carrinho. Ausente na primeira visita. */
                "X-Cart-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cart_api_cart_delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID do carrinho. Ausente na primeira visita. */
                "X-Cart-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_cart_items_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID do carrinho. Ausente na primeira visita. */
                "X-Cart-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_cart_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID do carrinho. Ausente na primeira visita. */
                "X-Cart-Id"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_cart_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID do carrinho. Ausente na primeira visita. */
                "X-Cart-Id"?: string | null;
            };
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout_api_checkout_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID do carrinho. Ausente na primeira visita. */
                "X-Cart-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Pagamento recusado */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Carrinho não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Carrinho vazio */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_orders__order_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
